<?php
$lancers = array(
		"asana" 				=> "Asana"
	,	"aurora" 				=> "Aurora"
	,	"blackburn" 			=> "Blackburn"
	,	"brynn"	  				=> "Brynn"
	,	"celeste" 				=> "Celeste"
	,	"drfinn"	  			=> "Dr._Finn"
	,	"elle" 					=> "Elle"
	,	"garrison" 				=> "Garrison"
	,	"gremolitionsinc"		=> "Gremolitions_Inc."
	,	"grey"	  				=> "Grey"
	,	"helio" 				=> "Helio"
	,	"juno"	  				=> "Juno"
	,	"kaigin" 				=> "Kaigin"
	,	"khita" 				=> "Khita"
	,	"lockwood" 				=> "Lockwood"
	,	"magnus" 				=> "Magnus"
	,	"meridian" 				=> "Meridian"
	,	"nev3"	  				=> "Nev"
	,	"nix" 					=> "Nix"
	,	"orion"	  				=> "Orion"
	,	"oz" 					=> "Oz"
	,	"phaedra" 				=> "Phaedra"
	,	"pup" 					=> "PuP"
	,	"quark"	  				=> "Quark"
	,	"rampart" 				=> "Rampart"
	,	"rask"	  				=> "Rask"
	,	"suren" 				=> "Su-Ren"
	,	"titus" 				=> "Titus"
	,	"tolren" 				=> "Tol-Ren"
	,	"zuki" 					=> "Zuki"
	,	"isadora" 				=> "Isadora"

);
